
NAME=app

all: clean $(NAME)
	./$(NAME)

$(NAME): 
	rm -f $(NAME)
	c++ -std=c++98 -Wall -Wextra -o $(NAME) test.cpp # -g -fsanitize=address

clean:
	rm -f $(NAME)


# ./scripts /php /hfghj/hgfhghjg.php